
services:

  # backend
  backend:
      build:
        context: .
        dockerfile: backend/Dockerfile
      
      container_name: perguntAI-backend
      restart: unless-stopped
      
      env_file:
        - ./backend/.env
      
      ports:
        - "5111:5111"
      
      networks:
        - perguntAI-network

  # frontend
  frontend:
      build:
        context: .
        dockerfile: frontend/Dockerfile
      
      container_name: perguntAI-frontend
      restart: unless-stopped
      
      depends_on:
        - backend
      
      ports:
        - "3000:80"
      
      networks:
        - perguntAI-network

  # ollama
  ollama:
      image: ollama/ollama
      container_name: perguntAI-ollama
      restart: unless-stopped

      ports:
        - "11434:11434"

      volumes:
        - ollama_data:/root/.ollama

      networks:
        - perguntAI-network


volumes:
    ollama_data:



networks:
    perguntAI-network:
      driver: bridge