
// imports
import axios from "axios";

// import interfaces
import { iGenerationOptions, iStudyMaterial } from "@interfaces/user.interfaces";
import { iQuestion} from "@interfaces/model.interfaces";

// import error handler
import { getErrorMessage } from "@root/utils/errorHandler";

// import env
import dotenv from 'dotenv';
dotenv.config({});



// model service - class
class ModelService {
   getErrorMessage = getErrorMessage;

   // ollama request - public
   public async ollamaRequest(
      questionOptions: iGenerationOptions,
      studyMaterial: iStudyMaterial 
   ): Promise<iQuestion[]> {
      try{
         // validations
         if(questionOptions.numQuestions <= 0) throw new Error('❌ Questions is empty');
         if(studyMaterial.text === '') throw new Error('❌ Text material is empty');

         // prompt generation
         const prompt: string = `         
            You are an AI generating study questions.

            Based on the text provided below, generate exactly ${questionOptions.numQuestions} 
            questions of type ${questionOptions.questionType}
            with difficulty level ${questionOptions.difficulty}, and in language ${questionOptions.language}.

            Each question must be consistent with the content and contain acceptable answers (synonyms and short variations).

            Mandatory rules:
               1. Return only plain JSON (no explanation, no comments).
               2. The JSON must be a list of objects following the format below exactly:
               [
                  {
                     "id": "string (UUID generated by you, e.g., q1)",
                     "prompt": "question text",
                     "acceptableAnswers": ["answer1", "answer2"],
                     "type": "open" or "multipleChoice" or "mix",
                     "choices": ["choice1", "choice2", "choice3", "choice4"] (optional)
                  }
               ]
               3. If the question type is "open", DO NOT include the "choices" field.
               4. All answers must be consistent with the text provided.
               5. Do not repeat questions or generate generic answers.

            Base text: ${studyMaterial.text}
         `
         // get model response
         const llm_response = await axios.post(process.env.OLLAMA_URL as string, {
            'model': 'mistral',
            'prompt': prompt,
            'stream': false
         });
         const result = typeof llm_response.data === 'string' 
         ? llm_response.data
         : llm_response.data.response;

         // clean result
         const clean = result.trim();

         // convert clean result to object
         const parsedResult: iQuestion[] = JSON.parse(clean);
         return parsedResult;
      }
      catch(error: unknown){
         console.log('Ollama request service internal error', this.getErrorMessage(error));
         return [];
      }
   };

};
export const modelService: ModelService = new ModelService();