
// import interfaces
import { iGenerationOptions } from "@interfaces/user.interfaces";
import { iStudyMaterial } from "@interfaces/user.interfaces";
import { iQuestionSession, iQuestionsSet, iQuestion } from "@interfaces/model.interfaces";


// ollama question request - prompt
export const prompt_question = (
   questionOptions: iGenerationOptions,
   studyMaterial: iStudyMaterial,
): string => {
   if(questionOptions.language === 'portuguese' || 'português'){
      return ` Você é uma IA responsável por gerar perguntas de estudo.

         Com base no texto fornecido abaixo, gere exatamente ${questionOptions.numQuestions} 
         perguntas do tipo ${questionOptions.questionType}, 
         com nível de dificuldade ${questionOptions.difficulty}, 
         e no idioma ${questionOptions.language}.

         Cada pergunta deve ser coerente com o conteúdo do texto e conter respostas 
         aceitáveis (sinônimos e variações curtas).

         Regras obrigatórias:
            1. Retorne apenas JSON puro (sem explicações, comentários ou texto fora do objeto).
            2. O JSON deve ser uma lista de objetos seguindo exatamente o formato abaixo:
            [
               {
                  "id": "string (UUID gerado por você, ex: q1)",
                  "prompt": "texto da pergunta",
                  "acceptableAnswers": ["resposta1", "resposta2"],
                  "type": "open" ou "multipleChoice" ou "mix",
                  "choices": ["opção1", "opção2", "opção3", "opção4"] (opcional)
               }
            ]
            3. Se o tipo de pergunta for "open", NÃO inclua o campo "choices".
            4. Todas as respostas devem estar coerentes com o texto base.
            5. Não repita perguntas e não gere respostas genéricas.

         Texto base: ${studyMaterial.text}
         `
   }else{
      return ` 
         You are an AI generating study questions.
   
         Based on the text provided below, generate exactly ${questionOptions.numQuestions} 
         questions of type ${questionOptions.questionType}
         with difficulty level ${questionOptions.difficulty}, and in language ${questionOptions.language}.
   
         Each question must be consistent with the content and contain acceptable answers 
         (synonyms and short variations).
   
         Mandatory rules:
            1. Return only plain JSON (no explanation, no comments).
            2. The JSON must be a list of objects following the format below exactly:
            [
               {
                  "id": "string (UUID generated by you, e.g., q1)",
                  "prompt": "question text",
                  "acceptableAnswers": ["answer1", "answer2"],
                  "type": "open" or "multipleChoice" or "mix",
                  "choices": ["choice1", "choice2", "choice3", "choice4"] (optional)
               }
            ]
            3. If the question type is "open", DO NOT include the "choices" field.
            4. All answers must be consistent with the text provided.
            5. Do not repeat questions or generate generic answers.
   
         Base text: ${studyMaterial.text}
      `;
   }
}


// ollama user response request - prompt
export const prompt_answer = (
   questionId: string,
   userResponse: string,
   questionSession: iQuestionSession
): string => {
   if(questionSession.questionSet.options.language === 'portuguese' || 'português'){
      return ` Você é uma IA responsável por avaliar a resposta de um estudante em uma sessão de estudos.
   
         Analise se a resposta do estudante está correta ou incorreta com base na pergunta original e 
         nas respostas aceitáveis.
   
         ---
   
         🔹 Contexto da sessão:
         ${JSON.stringify(questionSession, null, 2)}
   
         🔹 Dados da resposta:
         - ID da questão: ${questionId}
         - Resposta do estudante: "${userResponse}"
   
         ---
   
         💡 IMPORTANTE:
         - Gere o feedback inteiramente em ${questionSession.questionSet.options.language}.
         - Retorne APENAS JSON, sem comentários, sem markdown, sem explicações fora do objeto.
         - Se a resposta estiver errada ou parcialmente correta, o campo "feedback" 
         deve conter uma frase curta em ${questionSession.questionSet.options.language}.
         - Nunca misture idiomas.
   
         ---
   
         O JSON DE SAÍDA DEVE SEGUIR EXATAMENTE ESTE MODELO:
   
         EXEMPLO (em ${questionSession.questionSet.options.language}):
   
         {
            "questionId": "q1",
            "userResponse": "São Paulo",
            "isCorrect": false,
            "feedback": "Incorreto. A resposta certa é: Ulm."
         }
   
         Agora avalie a questão indicada.
      `
   }else{
      return ` You are an AI responsible for evaluating a student's answer in an active study session.

         Evaluate whether the student's current response is correct or incorrect 
         based on the original question set and its acceptable answers.

         Context:
            - You will receive the entire study session object ${questionSession}.
            - Use only the question whose "id" matches the provided questionId.
            - Compare the user's response ${userResponse} against the 
            "acceptableAnswers" ${questionSession.questionSet.questions} field 
            of that question (case-insensitive and allowing close synonyms).
            - Your feedback will be in this language: ${questionSession.questionSet.options.language}

         Rules:
            1. Return only plain JSON (no explanations, no markdown, no comments).
            2. The JSON must be a single object following EXACTLY this format:
               {
                  "questionId": "string (same as provided)",
                  "userResponse": "string (student's answer)",
                  "isCorrect": boolean,
                  "feedback": "string (short feedback, optional if correct) and need be
                  is this language: ${questionSession.questionSet.options.language}"
               }
            3. Mark as correct if the user's response matches or closely resembles 
               any acceptable answer (ignore case, accents, punctuation differences).
            4. If incorrect or partially correct, return a short feedback string like:
               - "Almost correct, but missing a key detail."
               - "Incorrect. The correct answer is: <answer>."
               - "Close, but check the term <keyword>."
            5. Do NOT modify the session or create new data.
            6. Base your judgment strictly on the provided questionSession content.

         Evaluate the following session data:
         {
            "questionId": "${questionId}",
            "userResponse": "${userResponse}",
            "questionSession": ${JSON.stringify(questionSession, null, 2)}
         }
      `
   }

};