
// import interfaces
import { iGenerationOptions } from "@interfaces/user.interfaces";
import { iStudyMaterial } from "@interfaces/user.interfaces";
import { iQuestionSession, iQuestionsSet, iQuestion } from "@interfaces/model.interfaces";


// ollama question request - prompt
export const prompt_question = (
   questionOptions: iGenerationOptions,
   studyMaterial: iStudyMaterial,
): string => {
   return ` 
      You are an AI generating study questions.

      Based on the text provided below, generate exactly ${questionOptions.numQuestions} 
      questions of type ${questionOptions.questionType}
      with difficulty level ${questionOptions.difficulty}, and in language ${questionOptions.language}.

      Each question must be consistent with the content and contain acceptable answers (synonyms and short variations).

      Mandatory rules:
         1. Return only plain JSON (no explanation, no comments).
         2. The JSON must be a list of objects following the format below exactly:
         [
            {
               "id": "string (UUID generated by you, e.g., q1)",
               "prompt": "question text",
               "acceptableAnswers": ["answer1", "answer2"],
               "type": "open" or "multipleChoice" or "mix",
               "choices": ["choice1", "choice2", "choice3", "choice4"] (optional)
            }
         ]
         3. If the question type is "open", DO NOT include the "choices" field.
         4. All answers must be consistent with the text provided.
         5. Do not repeat questions or generate generic answers.

      Base text: ${studyMaterial.text}

   `;
}


// ollama user response request - prompt
export const prompt_answer = (
   questionId: string,
   userResponse: string,
   questionSession: iQuestionSession
): string => {
   return ` You are an AI responsible for evaluating a student's answer in an active study session.

      Evaluate whether the student's current response is correct or incorrect 
      based on the original question set and its acceptable answers.

      Context:
         - You will receive the entire study session object ${questionSession}.
         - Use only the question whose "id" matches the provided questionId.
         - Compare the user's response ${userResponse} against the 
         "acceptableAnswers" ${questionSession.questionSet.questions} field 
         of that question (case-insensitive and allowing close synonyms).
         - Your feedback will be in this language: ${questionSession.questionSet.options.language}

      Rules:
         1. Return only plain JSON (no explanations, no markdown, no comments).
         2. The JSON must be a single object following EXACTLY this format:
            {
               "questionId": "string (same as provided)",
               "userResponse": "string (student's answer)",
               "isCorrect": boolean,
               "feedback": "string (short feedback, optional if correct)"
            }
         3. Mark as correct if the user's response matches or closely resembles 
            any acceptable answer (ignore case, accents, punctuation differences).
         4. If incorrect or partially correct, return a short feedback string like:
            - "Almost correct, but missing a key detail."
            - "Incorrect. The correct answer is: <answer>."
            - "Close, but check the term <keyword>."
         5. Do NOT modify the session or create new data.
         6. Base your judgment strictly on the provided questionSession content.

      Evaluate the following session data:
      {
         "questionId": "${questionId}",
         "userResponse": "${userResponse}",
         "questionSession": ${JSON.stringify(questionSession, null, 2)}
      }
   `
};