
// import interfaces
import { iGenerationOptions } from "@interfaces/user.interfaces";
import { iStudyMaterial } from "@interfaces/user.interfaces";
import { iQuestionSession, iQuestionsSet, iQuestion } from "@interfaces/model.interfaces";


// utils
let questionType = '';
let difficulty = '';
let language = 'português';

// question translate setup
const questions_translate_setup = (
   questionOptions: iGenerationOptions
): void =>{
   switch (questionOptions.questionType) {
      case 'mix':
         questionType = 'misturado';
         break;
      case 'multipleChoice':
         questionType = 'múltipla escolha'
         break;
      case 'open':
         questionType = 'aberto'
         break;
      default:
         break;
   }
               
   switch (questionOptions.difficulty) {
      case 'basic':
         difficulty = 'básico'
         break;
      case 'intermediate':
         difficulty = 'intermediário'
         break;
      case 'advanced':
         difficulty = 'avançado'
         break;
      default:
         break;
   }
};


// ollama question request - prompt
export const prompt_question = (
   questionOptions: iGenerationOptions,
   studyMaterial: iStudyMaterial,
): string => {
   // translate
   questions_translate_setup(questionOptions);

   // prompt
   if(questionOptions.language === 'portuguese'){
      return `
         Você é uma IA responsável por gerar perguntas de estudo.

         Com base no texto fornecido abaixo, gere exatamente ${questionOptions.numQuestions} 
         perguntas do tipo ${questionType}, 
         com nível de dificuldade ${difficulty},
         e no idioma português.

         Cada pergunta deve ser coerente com o conteúdo do texto e conter respostas 
         aceitáveis (sinônimos e variações curtas).

         ! Regras obrigatórias:
         1. Retorne apenas JSON puro (sem explicações, comentários ou texto fora do objeto).
         2. O JSON deve ser uma lista de objetos seguindo exatamente o formato abaixo:
         [
         {
            "id": "string (UUID gerado por você, ex: q1)",
            "prompt": "texto da pergunta",
            "acceptableAnswers": ["resposta correta 1", "resposta correta 1"],
            "type": "open" ou "multipleChoice" ou "mix",
            "choices": [
               "A) alternativa incorreta",
               "B) alternativa correta",
               "C) alternativa incorreta"
            ] (opcional)
         }
         ]
         3. Se o tipo de pergunta for "open", NÃO inclua o campo "choices" gere as "acceptableAnswers", mas não faça referência a elas na pergunta.
         4. Se o tipo de pergunta for "mix", faça perguntas que alternem entre com e sem o campo "choices"
         5. Todas as respostas devem estar coerentes com o texto base.
         6. Não repita perguntas e não gere respostas genéricas.

         ! Regras adicionais PARA perguntas do tipo "multipleChoice" E que possui o campo "choices":
         - Cada pergunta deve ter exatamente 3 alternativas.
         - A alternativa correta deve ser SEMPRE a letra **B)**.
         - A alternativa **B)** deve ser literalmente igual a um dos valores de "acceptableAnswers".
         - As alternativas **A)** e **C)** devem ser erradas, porém plausíveis.
         - As alternativas A e C não devem ser sinônimos da correta.
         - NÃO gere alternativas vagas ou genéricas.
         - Nunca coloque mais de uma alternativa correta.
         - O formato das alternativas deve ser STRICTO e SEMPRE assim:
         "A) ...",
         "B) ...",
         "C) ..."

         ! Saída fora desse formato deve ser considerada inválida.

         Texto base:
         ${studyMaterial.text}
      `
   }else{
      return ` 
         You are an AI responsible for generating study questions.

         Based on the text provided below, generate exactly ${questionOptions.numQuestions} 
         questions of type ${questionType},
         with difficulty level ${difficulty},
         and in the English language.

         Each question must be consistent with the content of the text and contain
         acceptable answers (synonyms and short variations).

         ! Mandatory rules:
         1. Return ONLY pure JSON (no explanations, no comments).
         2. The JSON must be a list of objects following this exact structure:
         [
         {
            "id": "string (UUID generated by you, e.g., q1)",
            "prompt": "question text",
            "acceptableAnswers": ["correct answer 1", "correct answer 2"],
            "type": "open" or "multipleChoice" or "mix",
            "choices": [
               "A) incorrect option",
               "B) correct option",
               "C) incorrect option"
            ] (optional)
         }
         ]
         3. If the question type is "open", DO NOT include the "choices" field, generate the "acceptableAnswers", but not reference them in the question.
         4. If the question type is "mix", ask questions that alternate between having and not having the "choices" field. 
         5. All answers must be coherent with the source text.
         6. Do not repeat questions or generate generic content.

         ! Additional rules for MULTIPLE-CHOICE questions AND that has the "choices" field:
         - Each question MUST have exactly 3 options.
         - The correct option MUST ALWAYS be letter **B)**.
         - Option **B)** MUST match exactly one of the values in "acceptableAnswers".
         - Options **A)** and **C)** must be incorrect but plausible.
         - A and C cannot be synonyms of the correct option.
         - DO NOT generate vague or generic options.
         - Never include more than one correct option.
         - The format of the choices MUST follow this EXACT pattern:
         "A) ...",
         "B) ...",
         "C) ..."

         ! Any output not following this structure is invalid.

         Base text:
         ${studyMaterial.text}
      `;
   }
}


// ollama user response request - prompt
export const prompt_answer = (
   questionId: string[],
   userResponses: string[],
   questionSession: iQuestionSession
): string => {
   if(
      questionSession.questionSet.options.language === 'portuguese' || 
      questionSession.questionSet.options.language === 'português'
   ){
      return ` Você é uma IA responsável por avaliar a resposta de um estudante em uma sessão de estudos.
   
         Analise se a resposta do estudante está correta ou incorreta com base na pergunta original e 
         nas respostas aceitáveis.
   
         ---
   
         🔹 Contexto da sessão:
         ${JSON.stringify(questionSession, null, 2)}
   
         🔹 Dados da resposta:
         - ID's da questões: ${questionId}
         - Respostas do estudante: "${userResponses}"
   
         ---
   
         💡 IMPORTANTE:
         - Gere o feedback inteiramente em ${questionSession.questionSet.options.language}.
         - Retorne APENAS JSON, sem comentários, sem markdown, sem explicações fora do objeto.
         - Se a resposta estiver errada ou parcialmente correta, o campo "feedback" 
         deve conter uma frase curta em ${questionSession.questionSet.options.language}.
         - Nunca misture idiomas.
   
         ---
   
         O JSON DE SAÍDA DEVE SEGUIR EXATAMENTE ESTE MODELO:
   
         EXEMPLO (em português):

         [
            {
               "questionId": "q1",
               "userResponse": "São Paulo",
               "isCorrect": false,
               "feedback": "Incorreto. A resposta certa é: Ulm."
            },
            repete o objeto (caso haja mais questões)
         ]
   
         Agora avalie a questão indicada.
      `
   }else{
      return ` You are an AI responsible for evaluating a student's answer in an active study session.

         Evaluate whether the student's current response is correct or incorrect 
         based on the original question set and its acceptable answers.

         Context:
            - You will receive the entire study session object ${questionSession}.
            - Use only the question whose "id" matches the provided questionId.
            - Compare the user's response ${userResponses} against the 
            "acceptableAnswers" ${questionSession.questionSet.questions} field 
            of that question (case-insensitive and allowing close synonyms).
            - Your feedback will be in this language: ${questionSession.questionSet.options.language}

         Rules:
            1. Return only plain JSON (no explanations, no markdown, no comments).
            2. The JSON must be a single object following EXACTLY this format:
               [
                  {
                     "questionId": "string (same as provided)",
                     "userResponse": "string (student's answer)",
                     "isCorrect": boolean,
                     "feedback": "string (short feedback, optional if correct) and need be
                     is this language: english"
                  }
                  repeat the object (if there's more questions)
               ]
            3. Mark as correct if the user's response matches or closely resembles 
               any acceptable answer (ignore case, accents, punctuation differences).
            4. If incorrect or partially correct, return a short feedback string like:
               - "Almost correct, but missing a key detail."
               - "Incorrect. The correct answer is: <answer>."
               - "Close, but check the term <keyword>."
            5. Do NOT modify the session or create new data.
            6. Base your judgment strictly on the provided questionSession content.

         Evaluate the following session data:
         {
            "questionId": "${questionId}",
            "userResponse": "${userResponses}",
            "questionSession": ${JSON.stringify(questionSession, null, 2)}
         }
      `
   }

};